### ISSUE TITLE
Timestamp precision

### ISSUE THREAD

**Issue by donmendelson** [FIXTradingCommunity/fix-json-encoding-spec#2]
The spec mentions the limitations of the JavaScript Date object, but millisecond precision will be insufficient for some users. MiFID II requires microsecond or nanosecond precision, so the GTC has developed Time Precision Enhancement Technical Addendum that covers this topic.

**Comment by mgatny** [comment]
Thanks, @donmendelson -- is this the document you are referring to? [EP206 Clock Synchronization Datatype Enhancement](http://www.fixtradingcommunity.org/pg/extensions/extension-pack?ExtensionID=EP206)

**Comment by donmendelson** [comment]
@mgatny , yes, and there is another one being developed to make it apply to earlier versions of FIX.

**Comment by mgatny** [comment]
- [ ] Recommend ISO 8601 when converting to/from timestamp
- [ ] Reference [EP206 Clock Synchronization Datatype Enhancement](http://www.fixtradingcommunity.org/pg/extensions/extension-pack?ExtensionID=EP206)
